services:
  # Backend Python service
  - type: web
    name: youtube-script-generator
    env: python
    buildCommand: pip install flask-login flask-sqlalchemy Werkzeug gunicorn && pip install -r requirements.txt
    startCommand: cd backend && gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: DATABASE_URL
        value: sqlite:///yt_autom.db
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://yt-autom-frontend.onrender.com

  # Frontend React service
  - type: web
    name: youtube-script-interface
    env: static
    buildCommand: cd youtube-script-interface && npm install && npm run build
    staticPublishPath: ./youtube-script-interface/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://youtube-script-generator.onrender.com
