services:
  # Backend Python service
  - type: web
    name: youtube-script-generator
    env: python
    buildCommand: pip install flask-login flask-sqlalchemy Werkzeug gunicorn && pip install -r requirements.txt
    startCommand: cd backend && gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: DATABASE_URL
        value: sqlite:///yt_autom.db
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://yt-autom-frontend.onrender.com

  # Frontend React service - configuration spéciale pour SPA
  - type: web
    name: youtube-script-interface
    env: node
    buildCommand: cd youtube-script-interface && npm install && npm run build
    startCommand: cd youtube-script-interface && node rewrite.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://youtube-script-generator.onrender.com
